name: Run Unit Tests

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-13]
    runs-on: ${{ matrix.platform }}
 
    steps:
    - name: Checkout Demo
      uses: actions/checkout@v4
    - name: Upload releases
      uses: actions/upload-artifact@v4
      with:
        name: ${{ runner.os }}
        retention-days: 1
        path: ${{ runner.os }}.zip 
    - name: Upload cppDeploy
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v4
      with:
        name: cppDeploy
        retention-days: 1
        path: cppDeploy.zip
  deploy-nightly:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v4
      - name: Display structure of downloaded files
        run: ls -R
      - name: Create nightly release
        uses: ncipollo/release-action@v1
        with:
          name: "Nightly Build"
          artifacts: "Windows.zip, Linux.zip, macOS.zip"
          tag: nightly
          prerelease: true
          allowUpdates: true
          removeArtifacts: true
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}
